XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX
      XXXXXX
      XXXXXX XXXXX
      XXXXXXXXXXXX XXXXX
      XXXXXXXXXXX XXXX

      X
    XXXXXXXX
  XXXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXXXXXXXXXXXXX
        XXXXX

      XXXXX
    XXXXXX
  XXXXXX
XXXXXX

  XXXX XXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX

   BBB B BB BBBBBBBBBB

    XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
  XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  XXXXXX
    XXXXXX
    XXXXXX

    BBBBBB






XXXXXX

XXXXXX
  XXXXXX
  XXXXXXXX

  XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
XXXXXXX