# Generated by Django 3.2.16 on 2023-02-14 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 6, 17, 36, 714321)),
        ),
    ]
