# Generated by Django 3.2.16 on 2023-02-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='', max_length=70),
        ),
    ]
